from aiogram.types import InlineKeyboardButton,InlineKeyboardMarkup,KeyboardButton,ReplyKeyboardMarkup

def main_menu(url): return InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text='📝 Заполнить анкету',callback_data='user:application')],[InlineKeyboardButton(text='💬 Поддержка',callback_data='user:support'),InlineKeyboardButton(text='ℹ️ Информация',callback_data='user:info')],[InlineKeyboardButton(text='📢 Наш канал',url=url)]])
def cancel_menu(): return ReplyKeyboardMarkup(keyboard=[[KeyboardButton(text='❌ Отменить')]],resize_keyboard=True)
def preview_kb(): return InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text='✅ Отправить анкету',callback_data='app:submit')],[InlineKeyboardButton(text='✏️ Заполнить заново',callback_data='app:restart'),InlineKeyboardButton(text='❌ Отменить',callback_data='app:cancel')]])
def app_admin_kb(aid,uid): return InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text='✅ Принять',callback_data=f'admin:app:accept:{aid}:{uid}'),InlineKeyboardButton(text='❌ Отклонить',callback_data=f'admin:app:reject:{aid}:{uid}')],[InlineKeyboardButton(text='💬 Написать пользователю',callback_data=f'admin:reply:user:{uid}:0')],[InlineKeyboardButton(text='🚫 Заблокировать',callback_data=f'admin:block:{uid}:application:{aid}')]])
def ticket_admin_kb(tid,uid): return InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text='💬 Ответить пользователю',callback_data=f'admin:reply:ticket:{uid}:{tid}')],[InlineKeyboardButton(text='✅ Закрыть обращение',callback_data=f'admin:ticket:close:{tid}:{uid}')],[InlineKeyboardButton(text='🚫 Заблокировать пользователя',callback_data=f'admin:block:{uid}:ticket:{tid}')]])
def panel_kb(): return InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text='📝 Новые анкеты',callback_data='panel:apps'),InlineKeyboardButton(text='💬 Открытые обращения',callback_data='panel:tickets')],[InlineKeyboardButton(text='👥 Пользователи',callback_data='panel:users'),InlineKeyboardButton(text='📊 Статистика',callback_data='panel:stats')],[InlineKeyboardButton(text='📣 Рассылка',callback_data='panel:broadcast'),InlineKeyboardButton(text='🚫 Заблокированные',callback_data='panel:blocked')],[InlineKeyboardButton(text='⚙️ Настройки',callback_data='panel:settings')]])
def broadcast_kb(): return InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text='✅ Начать рассылку',callback_data='broadcast:start'),InlineKeyboardButton(text='❌ Отменить',callback_data='broadcast:cancel')]])
